### ISSUE TITLE
Table View Doesn't Show on Initial Load

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam#344] opened 2015-09-16 20:25 UTC
See:
http://foam-framework.github.io/foam/foam/index.html?model=foam.demos.olympics.Controller

No data is present until you edit the columns and remove two or three.

**Comment by jlhughes** [comment] 2015-09-18 05:41
Experiencing the same thing.  In our case editing columns doesn't help.  The data doesn't render until our 'refresh' cycle runs which does a query on the DAOs but loads no data (expected).

**Comment by shepheb** [comment] 2015-09-18 11:29
I believe this was fixed yesterday with 644a0f15c164ed6db1c45ecfbadd9609e448c880. Olympics demo works for me on master.

Closing this issue; please reopen if there are still problems.

**Comment by jlhughes** [comment] 2015-09-18 12:38
We use tableFormatter liberally with lots of Elements.
Do we need to update all Element creation or just those in a tableFormatter?

Our calls are still
tableFormatter: function(arg) {
var e = E('span')
...

**Comment by jlhughes** [comment] 2015-09-18 12:40
Correct that, we have a mix of
tableFormatter(arg) and tableFormatter(arg, obj)
but we don't use the second argument 'obj' in any Element creation.
Joel

**Comment by adamvy** [comment] 2015-09-18 14:01
E('span') should work in my opinion, let me look in to this.

**Comment by adamvy** [comment] 2015-09-18 14:14
Found the real root problem, I will fix it so that your table formatters work as is.

**Comment by adamvy** [comment] 2015-09-18 14:28
Fix pushed.

**Closed by adamvy** 2015-09-18 14:28 UTC
Labels: bug

**Comment by jlhughes** [comment] 2015-09-18 15:05
Must be something our side. On the latest FOAM/master the rendering issue
persists regardless of the E/Element creation I use in our tableFormatters.
Joel

**Comment by adamvy** [comment] 2015-09-18 15:25
Try running with the devtools set to "break on all exceptions" and see if you tableFormatter is throwing an exception.

https://developer.chrome.com/devtools/docs/javascript-debugging#pause-on-exceptions

**Comment by jlhughes** [comment] 2015-09-18 15:43
Hi Adam

Does not render after (select):
                    var future = afuture();
                    this.src.where(AND.apply(null, [min,
max])).select(this.delegate)(function() {
                        this.delegate.removeAll();
                        this.delegate.select(sink, options)(future.set);
                    }.bind(this));
                    return future.get;

Does render after (refresh):
                this.src.where(expr).select(this.delegate)(ret);
where ret is just 'function(_){}'

Can you see any javascript mistakes, perhaps with the future?
Joel

**Comment by adamvy** [comment] 2015-09-18 15:47
In your second case, what does the select: method of your dao end up returning?

BTW your AND.apply can just be AND(min, max), since you know the number of arguments you're passing it.

**Comment by jlhughes** [comment] 2015-09-18 16:13
refresh select returns:
DeDupDAO(MDAO(Contact,TreeIndex(Id, value)))

This refresh.select call is returning the records the select.select also
returned, which indicates that the delegate is empty and the 'max' test
returned nothing.  So the select.select is not populating the cache
delegate.

        refresh_: function(ret) {

this.delegate.select(MAX(this.model.LAST_MODIFIED_DATE))(function(max) {
                var expr = TRUE;
                if (max && max.max) {
                    expr = GTD(this.model.LAST_MODIFIED_DATE, max.max);
                }

                if (this.model.name === 'Workorder') {
                    if (this.controller.lastDateQueryMin.compareTo(TRUE)) {
                        expr = AND.apply(null,
[this.controller.lastDateQueryMin, this.controller.lastDateQueryMax, expr]);
                    } else {
                        return;
                    }
                }
                this.src.where(expr).select(this.delegate)(ret);
            }.bind(this));
        }

select.select - the this.delegate is not being populated with the results
                    var future = afuture();
                    this.src.where(AND.apply(null, [min,
max])).select(this.delegate)(function() {
                        this.delegate.removeAll();
                        this.delegate.select(sink, options)(future.set);
                    }.bind(this));
                    return future.get;

**Comment by adamvy** [comment] 2015-09-18 16:20
Could this be caused by your NoSelectAllDAO which is preventing an initial select all?

The first time refresh_ is called delegate will be empty so you'll end up selecting all will you now?

**Comment by jlhughes** [comment] 2015-09-18 16:34
flow:
* initial select is blocked by NoSelectAllDAO, delegate is empty
* before the refresh runs (set interval to 60000), I set a date range,
searchmgr initiates a select, and SOQLDAO, invoked from select.select,
reports 10 records were returned, no table rendering
* refresh runs, reports 10 records returned, table renders.

Joel

**Comment by adamvy** [comment] 2015-09-18 16:56
Your delegate.removeAll() call looks wrong.

                    var future = afuture();
                    this.src.where(AND.apply(null, [min,
max])).select(this.delegate)(function() {
                        this.delegate.removeAll(); // This right here nukes all records in the delegate
                        this.delegate.select(sink, options)(future.set); // Causing this select to return nothing.
                    }.bind(this));
                    return future.get;

I believe you wanted this.delegate.removeAll() to go right before your this.src.where().select(), so as to empty the cache before populating it.

**Comment by jlhughes** [comment] 2015-09-18 17:05
Hi Adam
Yes, that was it. That was above yesterday and I remember moving it before
you added the 'future' which was the real 'fix' at the time for that code
block.

Thanks for the second pair of eyes, and now I understand how that block
works. With the removeAll I was really confused - and for good reason.  So
thanks for the javascript lessons as well.
We have a fully working system now.
Joel

**Comment by adamvy** [comment] 2015-09-18 18:03
Yay glad I could help!

Took me a while to find that too.  I kept doing other work and coming back to that snippet before it finally occurred to me.  Glad we got it sorted now.
